
USE dbepslaravel;

/* PROCEDIMIENTO CREAR ENTIDAD REGIONAL */
CREATE TABLE REGIONAL (

id_regional int AUTO_INCREMENT not null,
nombre_regional varchar(255) not null,
CONSTRAINT PK_regional primary key (id_regional));

/* PROCEDIMIENTO CREAR ENTIDAD ZONAL */
CREATE TABLE ZONAL (
id_zonal int AUTO_INCREMENT not null,
id_regional int not null,
zonal varchar(255) not null,
CONSTRAINT PK_zonal primary key (id_zonal),
CONSTRAINT FK_regional FOREIGN KEY (id_regional)REFERENCES REGIONAL (id_regional));

/* PROCEDIMIENTO CREAR ENTIDAD ESTADO */
CREATE TABLE ESTADO (
id_estado int not null,
estado varchar (15),
CONSTRAINT PK_estado primary key (id_estado));

/* PROCEDIMIENTO CREAR ENTIDAD IPS */
CREATE TABLE IPS (
cod_ips varchar(10)  NOT NULL,
nombre_ips varchar(255) NOT NULL,
razon_social varchar(255)NOT NULL,
id_zonal int NOT NULL,
id_estado int NOT NULL,
CONSTRAINT PK_ips primary key (cod_ips),
CONSTRAINT FK_zonal FOREIGN KEY (id_zonal)REFERENCES ZONAL (id_zonal),
CONSTRAINT FK_estado FOREIGN KEY (id_estado)REFERENCES ESTADO (id_estado));

/* PROCEDIMIENTO CREAR ENTIDAD PERFIL */
CREATE TABLE PERFIL(
id_perfil int not null,
perfil varchar (25)not null,
CONSTRAINT PK_perfil primary key (id_perfil));

/* PROCEDIMIENTO CREAR ENTIDAD USUARIO */
CREATE TABLE USUARIO(
id_usuario int AUTO_INCREMENT not null,
usuario int not null,
clave varchar(50),
nombres varchar(100) not null,
apellidos varchar(100) not null,
id_perfil int not null,
CONSTRAINT PK_usuario primary key (id_usuario),
CONSTRAINT FK_perfil FOREIGN KEY (id_perfil)REFERENCES PERFIL (id_perfil));

/* PROCEDIMIENTO CREAR ENTIDAD LISTA */
CREATE TABLE LISTA (
id_lista int AUTO_INCREMENT not null ,
id_regional int,
id_zonal int,
fecha_inicial date,
fecha_final date,
id_usuario int,
cod_ips varchar (10) not null, 
pregunta_1 varchar(20),
pregunta_2 varchar(20),
pregunta_3 varchar(20),
pregunta_4 varchar(20),
pregunta_5 varchar(20),
pregunta_6 varchar(20),
pregunta_7 int,
pregunta_8 int, 
pregunta_9 varchar(20),
pregunta_10 varchar(20),
pregunta_11 varchar(20),
pregunta_12 varchar(20),
pregunta_13 varchar(20),
pregunta_14 int,
pregunta_15 int,
pregunta_16 varchar(20),
pregunta_17 varchar(20),
pregunta_18 varchar(20),
pregunta_19 varchar(20),
pregunta_20 varchar(20),
observaciones varchar(255),
CONSTRAINT PK_lista primary key (id_lista),
CONSTRAINT FK_usuario FOREIGN KEY (id_usuario)REFERENCES USUARIO (id_usuario),
CONSTRAINT FK_ips FOREIGN KEY (cod_ips)REFERENCES IPS (cod_ips));

/* PROCEDIMIENTOS PARA ALIMENTAR TABLAS PRINCIPALES */

--- insertar datos tabla regional ---

insert into REGIONAL(nombre_regional)
values ('BOGOTA'),
       ('CENTRO - ORIENTE'),
	   ('EJE CAFETERO'),
	   ('NOR - OCCIDENTE'),
	   ('NOR - ORIENTE'),
	   ('NORTE'),
	   ('SUR - OCCIDENTE');
       
insert into ZONAL(id_regional,zonal)
values (1,'BOGOTA'),
       (6,'BOLIVAR'),
	   (2,'BOYACA'),
	   (2,'CALDAS'),
	   (2,'CASANARE'),
	   (7,'CAUCA'),
	   (6,'CESAR'),
       (4,'CORDOBA'),
	   (4,'DPTO ANTIOQUIA'),
	   (6,'DPTO ATLANTICO'),
	   (1,'DPTO CUNDINAMARCA'),
	   (3,'DPTO RISARALDA'),
	   (6,'DPTO SAN ANDRES'),
	   (5,'DPTO SANTANDER'),
	   (7,'DPTO VALLE DEL CAUCA'),
	   (2,'GUAVIARE'),
	   (2,'HUILA'),
	   (6,'LA GUAJIRA'),
	   (6,'MAGDALENA'),
	   (2,'META'),
	   (7,'NARIÑO'),
	   (5,'NORTE DE SANTANDER'),
	   (7,'PALMIRA'),
       (3,'QUINDIO'),
	   (6,'SUCRE'),
	   (2,'TOLIMA');    

insert into estado(id_estado,estado)
values (1,'ACTIVA'),
       (2,'INACTIVA');

insert into IPS(cod_ips,nombre_ips,razon_social,id_zonal,id_estado)
VALUES ('1988','GRANADA HILLS','CAFAM',1,1),
       ('1989','CALLE 51','CAFAM',1,1),
       ('3176','SABANALARGA','CENTRO MEDICO SAN JUAN E.U.',10,1),
       ('4289','UT FLORIDABLANCA','U.T FOSCAL - ESCANOGRAFIA S.A. UT',13,1),
       ('4846','UT BOLARQUI','U.T FOSCAL - ESCANOGRAFIA S.A. UT',13,1),
       ('5552','FACATATIVA','CLINICA CHIA',11,1),
       ('5845','COLOMBIA SALUDABLE','COLOMBIA SALUDABLE SEDE QUIBDO',9,1),
       ('5903','BARRANCABERMEJA','FORPRESALUD',13,1),
       ('6105','PASTO NORTE','SOCIEDAD MEDICA SURSALUD SAS',20,1),
       ('6106','PASTO SUR','SOCIEDAD MEDICA SURSALUD SAS',20,1),
       ('6155','CAOBOS','UBA VIHONCO SAS',21,1),
       ('6347','SOGAMOSO CENTRO','CLINICA CHIA',3,1),
       ('6380','ZIPAQUIRA','CLINICA CHIA',11,1),
       ('6381','CHIA','CLINICA CHIA',11,1),
       ('6383','TUNJA','CLINICA CHIA',3,1),
       ('6465','GUAVIARE','NUEVA SALUD INTEGRAL IPS SAS',15,1),
       ('6656','30 DE AGOSTO','INSTITUTO DE DIAGNOSTICO MEDICO S.A - IDIME S.A.',12,1),
       ('6657','DOS QUEBRADAS','INSTITUTO DE DIAGNOSTICO MEDICO S.A - IDIME S.A.',12,1),
       ('6658','AVENIDA GRAN COLOMBIA','UBA VIHONCO SAS',21,1),
       ('6996','YOPAL','SERVICIOS MEDICOS FAMEDIC S.A.S',5,1),
       ('7037','UT MURILLO','UT BARRANQUILLA NORTE PARA LA ATENCION USUARIOS NUEVA EPS',10,1),
       ('7039','UT BARRANQUILLA NORTE','UT BARRANQUILLA NORTE PARA LA ATENCION USUARIOS NUEVA EPS',10,1),
       ('7041','UT BARRANQUILLA CENTRO','UT BARRANQUILLA NORTE PARA LA ATENCION USUARIOS NUEVA EPS',10,1),
       ('7056','UT VILLA COLOMBIA','UT SALUD DE OCCIDENTE',14,1),
       ('7057','UT TEQUENDAMA','UT SALUD DE OCCIDENTE',14,1),
       ('7058','UT AV. VASQUEZ COBO','UT SALUD DE OCCIDENTE',14,1),
       ('7059','UT CALLE 26','UT SALUD DE OCCIDENTE',14,1),
       ('7061','UT MONTERIA','U.T SOLUCIONES INTEGRALES',8,1),
       ('7066','UT JARDIN','UT SANTA MARTA- CIENAGA PARA LA ATENCION USUARIOS NUEVA EPS',18,1),
       ('7067','UT POPAYAN','U.T. IPS NUEVA POPAYAN UT',6,1),
       ('7068','UT CIENAGA','UT SANTA MARTA- CIENAGA PARA LA ATENCION USUARIOS NUEVA EPS',18,1),
       ('7071','UT LAS DELICIAS','UT-VALLEDUPAR NORTE PARA LA ATENCION USUARIOS NUEVA EPS',7,1),
       ('7086','UT GENERAL DEL NORTE','U.T NORTOLIMPUS- ORGANIZACION CLINICA GENERAL DEL NORTE S.A.S-TR2',10,1),
       ('7087','UT AV. EL ARSENAL','UT CARTAGENA NORTE PARA LA ATENCION USUARIOS NUEVA EPS',2,1),
       ('7088','UT NEPS SOLEDAD','U.T NORTOLIMPUS- ORGANIZACION CLINICA GENERAL DEL NORTE S.A.S-TR2',10,1),
       ('7089','UT PEDRO DE HEREDIA','UT CARTAGENA NORTE PARA LA ATENCION USUARIOS NUEVA EPS',2,1),
       ('7090','UT LA PLAZUELA','UT CARTAGENA NORTE PARA LA ATENCION USUARIOS NUEVA EPS',2,1),
       ('7103','UT VIVA 1A CALI','UNION TEMPORAL VIVA CALI',14,1),
       ('7104','UT JAMUNDI','UNION TEMPORAL VIVA CALI',14,1),
       ('7107','UT VIVA 1A MEDELLIN','UNION TEMPORAL VIVA MEDELLIN',9,1),
       ('7163','SAN ALONSO','U.T FOSCAL - ESCANOGRAFIA S.A. UT',13,1),
       ('7236','UT AMERICAS','UNION TEMPORAL VIVA BOGOTA - VIVA 1A IPS SA',1,1),
       ('7237','UT SUBA','UNION TEMPORAL VIVA BOGOTA - VIVA 1A IPS SA',1,1),
       ('7255','UT CALLE 30','U.T NORTOLIMPUS- ORGANIZACION CLINICA GENERAL DEL NORTE S.A.S-TR2',10,1),
       ('7283','VILLAVICENCIO','SERVICIOS MEDICOS FAMEDIC S.A.S',19,1),
       ('7317','UT MARLY','UNION TEMPORAL VIVA BOGOTA - VIVA 1A IPS SA',1,1),
       ('7318','UT TOBERIN','UNION TEMPORAL VIVA BOGOTA - VIVA 1A IPS SA',1,1),
       ('7455','SALUD A TU LADO','IPS SALUD A TU LADO SAS',24,1),
       ('7998','UT POBLADO','UNION TEMPORAL VIVA MEDELLIN',9,1),
       ('7999','UT BELLO','UNION TEMPORAL VIVA MEDELLIN',9,1),
       ('8000','UT ENVIGADO','UNION TEMPORAL VIVA MEDELLIN',9,1),
       ('8002','UT PRADO','UNION TEMPORAL VIVA MEDELLIN',9,1),
       ('8003','UT VILLANUEVA','UNION TEMPORAL VIVA MEDELLIN',9,1),
       ('8006','UT ITAGUI','INTEGRACION EN SALUD PROMEDAN IPS UT',9,1),
       ('8014','FUNDADORES','INSTITUTO DE DIAGNOSTICO MEDICO S.A - IDIME S.A.',23,1),
       ('8015','UT MANIZALES CENTRO','UNION TEMPORAL VIVA MANIZALES',4,1),
       ('8040','UT ESTADIO','UNION TEMPORAL VIVA MEDELLIN',9,1),
       ('9668','VILLA DE SAN DIEGO','UNIDAD MEDICA VILLA DE SAN DIEGO ORLUZ LTDA',11,1),
       ('9883','UT CENTRO','INTEGRACION EN SALUD PROMEDAN IPS UT',9,1),
       ('9916','PROMOSALUD','PROMOSALUD IPS T&E LTDA',8,1),
       ('10022','UT LAURELES','UNION TEMPORAL VIVA MANIZALES',4,1),
       ('10192','GALENICA UT','CLINICA BOYACA GALENICA UT',3,1),
       ('10290','SANTA MARIA','E.A.T. CENTRO MEDICO SANTA MARIA I.P.S.',8,1),
       ('10419','LA PRIMERA','INSTITUTO DE DIAGNOSTICO MEDICO S.A - IDIME S.A.',14,1),
       ('10664','NEIVA CENTRO','INSTITUTO DE DIAGNOSTICO MEDICO S.A - IDIME S.A.',16,1),
       ('10693','CONSORCIO COMUNEROS','CONSORCIO COMUNEROS- LOS COMUNEROS HOSPITAL UNIVERSITARIO DE BUCARAMANGA S.A',13,1),
       ('10716','UT RIONEGRO','INTEGRACION EN SALUD PROMEDAN IPS UT',9,1),
       ('11129','FUSAGASUGA','BIENESTAR IPS S.A.S. - SANTA MARTA',11,1),
       ('11134','UT VILLAMARIA','UNION TEMPORAL VIVA MANIZALES',4,1),
       ('11285','UT SANTA MARIA DEL LAGO','UNION TEMPORAL VIVA BOGOTA - VIVA 1A IPS SA',1,1),
       ('11466','UT IBAGUE','UNION TEMPORAL VIVA TOLIMA',25,1),
       ('11467','UT ESPINAL','UNION TEMPORAL VIVA TOLIMA',25,1),
       ('11485','UT ALQUERIA','UNION TEMPORAL VIVA BOGOTA - VIVA 1A IPS SA',1,1),
       ('11486','UT BARRIOS UNIDOS','UNION TEMPORAL VIVA BOGOTA - VIVA 1A IPS SA',1,1),
       ('11487','UT KENNEDY','UNION TEMPORAL VIVA BOGOTA - VIVA 1A IPS SA',1,1),
       ('11488','UT PRIMAVERA','UNION TEMPORAL VIVA BOGOTA - VIVA 1A IPS SA',1,1),
       ('11492','GIRARDOT','BIENESTAR IPS S.A.S. - SANTA MARTA',11,1),
       ('11559','SOACHA','BIENESTAR IPS S.A.S. - SANTA MARTA',11,1),
       ('11562','FONTIBON','BIENESTAR IPS S.A.S. - SANTA MARTA',1,1),
       ('11563','CENTENARIO','BIENESTAR IPS S.A.S. - SANTA MARTA',1,1),
       ('11564','CIUDAD BOLIVAR','BIENESTAR IPS S.A.S. - SANTA MARTA',1,1),
       ('11565','BOSA','BIENESTAR IPS S.A.S. - SANTA MARTA',1,1),
       ('11707','UT RENACER RIOHACHA','UNION TEMPORAL CECAM IPS RENACER LTDA',17,1),
       ('11775','UT RESTREPO','UNION TEMPORAL VIVA BOGOTA - VIVA 1A IPS SA',1,1),
       ('11800','SEDE BUGALAGRANDE','SANACION Y VIDA I.P.S A.S',22,1),
       ('11801','SEDE CANDELARIA','SANACION Y VIDA I.P.S A.S',22,1),
       ('11802','SEDE EL CERRITO','SANACION Y VIDA I.P.S A.S',22,1),
       ('11803','SEDE FLORIDA','SANACION Y VIDA I.P.S A.S',22,1),
       ('11804','SEDE PALMIRA','SANACION Y VIDA I.P.S A.S',22,1),
       ('11805','SEDE PRADERA','SANACION Y VIDA I.P.S A.S',22,1),
       ('11806','SEDE TULUA','SANACION Y VIDA I.P.S A.S',22,1),
       ('11807','SEDE YUMBO','SANACION Y VIDA I.P.S A.S',14,1),
       ('11808','SEDE ZARZAL','SANACION Y VIDA I.P.S A.S',22,1),
       ('11809','SEDE BUENAVENTURA','SANACION Y VIDA I.P.S A.S',14,1),
       ('11810','SEDE BUGA','SANACION Y VIDA I.P.S A.S',22,1),
       ('11889','UT NORDVITAL','UT NORDVITAL IPS ESPECIALIDADES MEDICAS',21,1);       
       
SELECT * FROM REGIONAL;
SELECT * FROM zonal;
SELECT * FROM estado;
SELECT * FROM ips;
SELECT * FROM perfil;
SELECT * FROM usuario;
SELECT * FROM lista ;  

